"""Generate LaTeX tables and macros from analysis results.

  python src/make_tables.py --split main [--summary-path PATH] [--out-dir DIR]
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[1]

# Model short name mappings: must be letters-only for LaTeX macro names
MODEL_SHORT_NAMES = {
    "gpt-oss-120b": "OSS",
    "gemma-4-31b": "Gemma",
    "flash-lite": "Lite",
}

# Strategy short name mappings
STRATEGY_SHORT_NAMES = {
    "direct": "Direct",
    "indep3": "Indep",
    "critique3": "Critique",
    "multi3": "Multi",
}

STRATEGIES = ["direct", "indep3", "critique3", "multi3"]
STRATEGY_LABELS = {
    "direct": "Direct (1 call)",
    "indep3": "Independent×3 (vote)",
    "critique3": "Solve→Critique→Revise",
    "multi3": "Two scientists + adjudicator",
}


def format_percent(val: Optional[float], decimals: int = 1) -> str:
    """Format as percentage with given decimal places."""
    if val is None:
        return "??"
    return f"{val * 100:.{decimals}f}"


def format_num_with_sep(val: Optional[float]) -> str:
    """Format number with thousands separator."""
    if val is None:
        return "??"
    return f"{int(val):,}"


def format_p_value(val: Optional[float]) -> str:
    """Format p-value: 3 decimals or '<0.001'."""
    if val is None:
        return "??"
    if val < 0.001:
        return "<0.001"
    return f"{val:.3f}"


def mcnemar_p_text(val: Optional[float]) -> str:
    """Same as format_p_value for brevity."""
    return format_p_value(val)


def generate_macros(summary: dict, out_path: Path) -> str:
    """Generate LaTeX macros from summary data.

    Returns the full macro text and writes to out_path.
    """
    lines = ["%% Generated by make_tables.py - LaTeX macros for results"]

    # Get all models and check which ones are present in data
    all_possible_models = list(MODEL_SHORT_NAMES.keys())
    present_models = [m for m in all_possible_models if m in summary]
    missing_models = [m for m in all_possible_models if m not in summary]

    # Define placeholder macros for missing models
    for model in missing_models:
        short_m = MODEL_SHORT_NAMES[model]
        lines.append(f"\\newcommand{{\\N{short_m}}}{{\\textbf{{??}}}}")
        lines.append(f"\\newcommand{{\\DisagreeN{short_m}}}{{\\textbf{{??}}}}")
        lines.append(f"\\newcommand{{\\DisagreeFrac{short_m}}}{{\\textbf{{??}}}}")
        for strat in STRATEGIES:
            short_s = STRATEGY_SHORT_NAMES[strat]
            lines.append(f"\\newcommand{{\\Acc{short_s}{short_m}}}{{\\textbf{{??}}}}")
            lines.append(f"\\newcommand{{\\AccCILo{short_s}{short_m}}}{{\\textbf{{??}}}}")
            lines.append(f"\\newcommand{{\\AccCIHi{short_s}{short_m}}}{{\\textbf{{??}}}}")
            lines.append(f"\\newcommand{{\\Tok{short_s}{short_m}}}{{\\textbf{{??}}}}")
            lines.append(f"\\newcommand{{\\CorrPerMtok{short_s}{short_m}}}{{\\textbf{{??}}}}")
            lines.append(f"\\newcommand{{\\DisagreeAcc{short_s}{short_m}}}{{\\textbf{{??}}}}")
        # Delta and McNemar
        for strat1 in STRATEGIES:
            for strat2 in STRATEGIES:
                if strat1 != strat2:
                    s1, s2 = STRATEGY_SHORT_NAMES[strat1], STRATEGY_SHORT_NAMES[strat2]
                    lines.append(f"\\newcommand{{\\Delta{s1}{s2}{short_m}}}{{\\textbf{{??}}}}")
                    lines.append(f"\\newcommand{{\\DeltaCILo{s1}{s2}{short_m}}}{{\\textbf{{??}}}}")
                    lines.append(f"\\newcommand{{\\DeltaCIHi{s1}{s2}{short_m}}}{{\\textbf{{??}}}}")
                    lines.append(f"\\newcommand{{\\McNemarP{s1}{s2}{short_m}}}{{\\textbf{{??}}}}")
        lines.append(f"\\newcommand{{\\SingleSampleAcc{short_m}}}{{\\textbf{{??}}}}")
        lines.append(f"\\newcommand{{\\OracleAcc{short_m}}}{{\\textbf{{??}}}}")
        for strat in ["critique3", "multi3"]:
            short_s = STRATEGY_SHORT_NAMES[strat]
            lines.append(f"\\newcommand{{\\Rescue{short_s}{short_m}}}{{\\textbf{{??}}}}")
            lines.append(f"\\newcommand{{\\Corrupt{short_s}{short_m}}}{{\\textbf{{??}}}}")

    # Generate macros for present models
    for model in present_models:
        data = summary[model]
        short_m = MODEL_SHORT_NAMES[model]

        # Basic counts
        lines.append(f"\\newcommand{{\\N{short_m}}}{{{data['n']}}}")
        lines.append(f"\\newcommand{{\\DisagreeN{short_m}}}{{{data['disagreement']['n']}}}")
        lines.append(f"\\newcommand{{\\DisagreeFrac{short_m}}}{{{format_percent(data['disagreement']['frac'], 0)}}}")

        # Per-strategy metrics
        for strat in STRATEGIES:
            strat_data = data["strategies"][strat]
            short_s = STRATEGY_SHORT_NAMES[strat]

            # Accuracy and CI
            acc = strat_data["accuracy"]
            ci_lo, ci_hi = strat_data["ci95"]

            lines.append(f"\\newcommand{{\\Acc{short_s}{short_m}}}{{{format_percent(acc, 1)}}}")
            lines.append(f"\\newcommand{{\\AccCILo{short_s}{short_m}}}{{{format_percent(ci_lo, 1)}}}")
            lines.append(f"\\newcommand{{\\AccCIHi{short_s}{short_m}}}{{{format_percent(ci_hi, 1)}}}")

            # Tokens per question
            tok = strat_data["tokens_per_q"]
            lines.append(f"\\newcommand{{\\Tok{short_s}{short_m}}}{{{format_num_with_sep(tok)}}}")

            # Correct per million tokens
            cpm = strat_data["correct_per_Mtok"]
            lines.append(f"\\newcommand{{\\CorrPerMtok{short_s}{short_m}}}{{{format_num_with_sep(cpm) if cpm else '??'}}}")

            # Disagreement subset accuracy
            disagree_data = data["disagreement"][strat]
            if disagree_data["rate"] is not None:
                lines.append(f"\\newcommand{{\\DisagreeAcc{short_s}{short_m}}}{{{format_percent(disagree_data['rate'], 1)}}}")
            else:
                lines.append(f"\\newcommand{{\\DisagreeAcc{short_s}{short_m}}}{{--}}")

        # Contrasts (deltas and McNemar)
        for contrast_key, contrast_data in data["contrasts"].items():
            # Parse contrast key: "strat1-strat2"
            parts = contrast_key.split("-")
            if len(parts) == 2:
                strat1, strat2 = parts[0], parts[1]
                short_s1 = STRATEGY_SHORT_NAMES.get(strat1)
                short_s2 = STRATEGY_SHORT_NAMES.get(strat2)
                if short_s1 and short_s2:
                    delta = contrast_data["delta"]
                    delta_ci_lo, delta_ci_hi = contrast_data["ci95"]
                    p_val = contrast_data["p_exact"]

                    # Delta as signed percentage points (1 decimal)
                    delta_str = f"{delta*100:+.1f}"
                    ci_lo_str = f"{delta_ci_lo*100:+.1f}"
                    ci_hi_str = f"{delta_ci_hi*100:+.1f}"

                    lines.append(f"\\newcommand{{\\Delta{short_s1}{short_s2}{short_m}}}{{{delta_str}}}")
                    lines.append(f"\\newcommand{{\\DeltaCILo{short_s1}{short_s2}{short_m}}}{{{ci_lo_str}}}")
                    lines.append(f"\\newcommand{{\\DeltaCIHi{short_s1}{short_s2}{short_m}}}{{{ci_hi_str}}}")
                    lines.append(f"\\newcommand{{\\McNemarP{short_s1}{short_s2}{short_m}}}{{{mcnemar_p_text(p_val)}}}")

        # Single sample and oracle accuracy
        lines.append(f"\\newcommand{{\\SingleSampleAcc{short_m}}}{{{format_percent(data['indep_single_sample_acc'], 1)}}}")
        lines.append(f"\\newcommand{{\\OracleAcc{short_m}}}{{{format_percent(data['indep_any_correct'], 1)}}}")

        # Rescue and corruption rates
        transitions = data.get("transitions", {})

        # Critique rescue/corruption
        critique_data = transitions.get("critique3_vs_indep3", {})
        if critique_data:
            rescue = critique_data.get("rescue", {})
            corrupt = critique_data.get("corruption", {})
            if rescue.get("rate") is not None:
                lines.append(f"\\newcommand{{\\RescueCritique{short_m}}}{{{format_percent(rescue['rate'], 1)}}}")
            else:
                lines.append(f"\\newcommand{{\\RescueCritique{short_m}}}{{--}}")
            if corrupt.get("rate") is not None:
                lines.append(f"\\newcommand{{\\CorruptCritique{short_m}}}{{{format_percent(corrupt['rate'], 1)}}}")
            else:
                lines.append(f"\\newcommand{{\\CorruptCritique{short_m}}}{{--}}")

        # Multi rescue/corruption
        multi_data = transitions.get("multi3_vs_indep3", {})
        if multi_data:
            rescue = multi_data.get("rescue", {})
            corrupt = multi_data.get("corruption", {})
            if rescue.get("rate") is not None:
                lines.append(f"\\newcommand{{\\RescueMulti{short_m}}}{{{format_percent(rescue['rate'], 1)}}}")
            else:
                lines.append(f"\\newcommand{{\\RescueMulti{short_m}}}{{--}}")
            if corrupt.get("rate") is not None:
                lines.append(f"\\newcommand{{\\CorruptMulti{short_m}}}{{{format_percent(corrupt['rate'], 1)}}}")
            else:
                lines.append(f"\\newcommand{{\\CorruptMulti{short_m}}}{{--}}")

    lines += extra_macros(summary)
    macro_text = "\n".join(lines)
    out_path.write_text(macro_text)
    return macro_text


CATEGORY_SHORT_NAMES = {"ProtocolQA": "ProtocolQA", "SeqQA": "SeqQA", "DbQA": "DbQA", "LitQA2": "LitQA", "SeqQA2": "SeqQAII"}


def extra_macros(summary: dict) -> list[str]:
    """Per-category accuracy \\Acc<Cat><S><M> and unanimous-subset accuracy \\UnanimousAcc<S><M>."""
    out = []
    for model, short_m in MODEL_SHORT_NAMES.items():
        data = summary.get(model)
        for strat, short_s in STRATEGY_SHORT_NAMES.items():
            for cat, short_c in CATEGORY_SHORT_NAMES.items():
                v = (data or {}).get("by_category", {}).get(cat, {}).get(strat)
                out.append(f"\\newcommand{{\\Acc{short_c}{short_s}{short_m}}}{{{format_percent(v, 1) if v is not None else '\\textbf{??}'}}}")
            u = (data or {}).get("disagreement", {}).get("unanimous_acc", {}).get(strat, {}).get("rate")
            out.append(f"\\newcommand{{\\UnanimousAcc{short_s}{short_m}}}{{{format_percent(u, 1) if u is not None else '\\textbf{??}'}}}")
    return out


def generate_results_table(summary: dict, out_path: Path) -> None:
    """Generate main results table (strategies × models)."""
    present_models = sorted([m for m in MODEL_SHORT_NAMES.keys() if m in summary],
                            key=lambda m: MODEL_SHORT_NAMES[m])
    if not present_models:
        out_path.write_text("% No models to display\n")
        return

    lines = [
        "\\begin{table}[h]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{l" + "cc" * len(present_models) + "}",
        "\\toprule",
        "Strategy & " + " & ".join([f"\\multicolumn{{2}}{{c}}{{{MODEL_SHORT_NAMES[m]}}}" for m in present_models]) + " \\\\",
        " & " + " & ".join(["Acc [95\\% CI] & Tok/Q"] * len(present_models)) + " \\\\",
        "\\midrule",
    ]

    for strat in STRATEGIES:
        short_s = STRATEGY_SHORT_NAMES[strat]
        row_parts = [f"\\textit{{{STRATEGY_LABELS[strat]}}}"]
        for model in present_models:
            short_m = MODEL_SHORT_NAMES[model]
            # Acc [CI]
            row_parts.append(f"\\Acc{short_s}{short_m}\\% [\\AccCILo{short_s}{short_m}\\%--\\AccCIHi{short_s}{short_m}\\%]")
            # Tokens
            row_parts.append(f"\\Tok{short_s}{short_m}")
        lines.append(" & ".join(row_parts) + " \\\\")

    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Accuracy and token usage by strategy and model.}",
        "\\label{tab:results}",
        "\\end{table}",
    ])

    out_path.write_text("\n".join(lines) + "\n")


def generate_contrasts_table(summary: dict, out_path: Path) -> None:
    """Generate paired contrasts table (vs Independent×3)."""
    present_models = sorted([m for m in MODEL_SHORT_NAMES.keys() if m in summary],
                            key=lambda m: MODEL_SHORT_NAMES[m])
    if not present_models:
        out_path.write_text("% No models to display\n")
        return

    lines = [
        "\\begin{table}[h]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{l" + "ccc" * len(present_models) + "}",
        "\\toprule",
        "Contrast vs Indep & " + " & ".join([f"\\multicolumn{{3}}{{c}}{{{MODEL_SHORT_NAMES[m]}}}" for m in present_models]) + " \\\\",
        " & " + " & ".join(["$\\Delta$ & 95\\% CI & McNemar $p$"] * len(present_models)) + " \\\\",
        "\\midrule",
    ]

    # Only show relevant contrasts: vs indep3
    contrasts_to_show = [("multi3", "indep3"), ("critique3", "indep3"), ("direct", "indep3")]

    for strat1, strat2 in contrasts_to_show:
        short_s1 = STRATEGY_SHORT_NAMES[strat1]
        short_s2 = STRATEGY_SHORT_NAMES[strat2]
        label = f"{STRATEGY_LABELS[strat1]} vs {STRATEGY_LABELS[strat2]}"

        row_parts = [f"\\textit{{{label[:30]}}}"]  # Truncate for readability
        for model in present_models:
            short_m = MODEL_SHORT_NAMES[model]
            # Delta + CI + McNemar p (delta already in percentage points)
            row_parts.append(
                f"\\Delta{short_s1}{short_s2}{short_m} & "
                f"[\\DeltaCILo{short_s1}{short_s2}{short_m}, \\DeltaCIHi{short_s1}{short_s2}{short_m}] & "
                f"\\McNemarP{short_s1}{short_s2}{short_m}"
            )
        lines.append(" & ".join(row_parts) + " \\\\")

    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Paired contrasts vs Independent×3 (vote). $\\Delta$ = difference in accuracy (pp).}",
        "\\label{tab:contrasts}",
        "\\end{table}",
    ])

    out_path.write_text("\n".join(lines) + "\n")


def generate_category_table(summary: dict, out_path: Path) -> None:
    """Generate per-category accuracy table (appendix-ready)."""
    present_models = sorted([m for m in MODEL_SHORT_NAMES.keys() if m in summary],
                            key=lambda m: MODEL_SHORT_NAMES[m])
    if not present_models:
        out_path.write_text("% No models to display\n")
        return

    # Collect all categories across all models
    all_categories = set()
    for model in present_models:
        all_categories.update(summary[model].get("by_category", {}).keys())
    all_categories = sorted(all_categories)

    if not all_categories:
        out_path.write_text("% No categories to display\n")
        return

    lines = [
        "\\begin{table}[h]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{l" + "c" * (len(present_models) * 5) + "}",
        "\\toprule",
        "Category & " + " & ".join([f"\\multicolumn{{5}}{{c}}{{{MODEL_SHORT_NAMES[m]}}}" for m in present_models]) + " \\\\",
        " & " + " & ".join(["D & I & C & M & Disagree"] * len(present_models)) + " \\\\",
        "\\midrule",
    ]

    for cat in all_categories:
        row_parts = [cat]
        for model in present_models:
            by_cat = summary[model].get("by_category", {}).get(cat, {})
            if by_cat:
                # D, I, C, M = direct, indep3, critique3, multi3
                d = by_cat.get("direct", None)
                i = by_cat.get("indep3", None)
                c = by_cat.get("critique3", None)
                m = by_cat.get("multi3", None)
                disagree = by_cat.get("disagreement_rate", None)

                d_str = f"{d*100:.1f}" if d is not None else "--"
                i_str = f"{i*100:.1f}" if i is not None else "--"
                c_str = f"{c*100:.1f}" if c is not None else "--"
                m_str = f"{m*100:.1f}" if m is not None else "--"
                disagree_str = f"{disagree*100:.1f}" if disagree is not None else "--"

                row_parts.extend([d_str, i_str, c_str, m_str, disagree_str])
            else:
                row_parts.extend(["--"] * 5)
        lines.append(" & ".join(row_parts) + " \\\\")

    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Per-category accuracy (D=Direct, I=Independent×3, C=Critique, M=Multi). Numbers are percentages.}",
        "\\label{tab:by-category}",
        "\\end{table}",
    ])

    out_path.write_text("\n".join(lines) + "\n")


def copy_figures(split: str, out_dir: Path) -> None:
    """Copy figure PDFs from results/figures/ to paper/figures/."""
    fig_src = ROOT / "results" / "figures"
    fig_dst = out_dir / "figures"

    if not fig_src.exists():
        print(f"Note: {fig_src} does not exist yet (figures generated by analyze.py)")
        return

    fig_dst.mkdir(parents=True, exist_ok=True)

    for pattern in [f"fig1_accuracy_{split}.pdf", f"fig2_efficiency_conflict_{split}.pdf"]:
        src_file = fig_src / pattern
        if src_file.exists():
            dst_file = fig_dst / pattern
            shutil.copy2(src_file, dst_file)
            print(f"Copied {src_file} → {dst_file}")
        else:
            print(f"Note: {src_file} not found")


def main():
    ap = argparse.ArgumentParser(
        description="Generate LaTeX tables and macros from analysis results."
    )
    ap.add_argument("--split", default="main", help="Split name (default: main)")
    ap.add_argument("--summary-path", help="Path to summary JSON (default: results/analysis/summary_<split>.json)")
    ap.add_argument("--out-dir", help="Output directory for LaTeX files (default: paper)")
    args = ap.parse_args()

    # Determine summary path
    if args.summary_path:
        summary_path = Path(args.summary_path)
    else:
        summary_path = ROOT / "results" / "analysis" / f"summary_{args.split}.json"

    # Determine output directory
    out_dir = Path(args.out_dir) if args.out_dir else ROOT / "paper"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Load summary
    if not summary_path.exists():
        print(f"{summary_path} does not exist; writing placeholder (??) macros and tables.")
        summary = {}
    else:
        summary = json.loads(summary_path.read_text())
    print(f"Loaded summary from {summary_path} with {len(summary)} models")

    # Generate outputs
    macros_path = out_dir / "results_macros.tex"
    generate_macros(summary, macros_path)
    print(f"Generated {macros_path}")

    results_table_path = out_dir / "results_tables.tex"
    generate_results_table(summary, results_table_path)
    print(f"Generated {results_table_path}")

    contrasts_table_path = out_dir / "results_contrasts_table.tex"
    generate_contrasts_table(summary, contrasts_table_path)
    print(f"Generated {contrasts_table_path}")

    category_table_path = out_dir / "appendix_category_table.tex"
    generate_category_table(summary, category_table_path)
    print(f"Generated {category_table_path}")

    # Copy figures
    copy_figures(args.split, out_dir)

    print("Done!")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
