"""Write every number the paper uses (paper/numbers.tex) and the prompt appendix (paper/prompts_appendix.tex)
from results/analysis/*.json and src/strategies.py, so the text never contains hand-copied values.

  python src/analyze.py --split main --models gpt-oss-120b gemma-4-31b flash-lite
  python src/think_vs_talk.py && python src/think_vs_talk.py ceiling
  python src/paper_numbers.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import strategies as ST  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
AN = ROOT / "results" / "analysis"
PAPER = ROOT / "paper"
MODEL = {"gpt-oss-120b": "OSS", "gemma-4-31b": "Gemma", "flash-lite": "Lite"}
STRAT = {"direct": "Direct", "indep3": "Vote", "critique3": "Critique", "multi3": "Debate"}
FAM = {"Flash-Lite": "Lite", "GPT-6 Luna": "Luna", "GPT-6 Sol": "Sol", "GPT-5.6 Terra": "Terra",
       "GPT-OSS-120B": "OSS", "Gemma 4 31B": "Gemma"}


def pct(x, d=1):
    return "??" if x is None else f"{100 * x:.{d}f}"


def pp(x, d=1):
    return "??" if x is None else f"{100 * x:+.{d}f}"


def main():
    L = ["% AUTO-GENERATED by src/paper_numbers.py -- do not edit by hand"]
    add = lambda k, v: L.append(f"\\newcommand{{\\{k}}}{{{v}}}")  # noqa: E731
    summ = json.loads((AN / "summary_main.json").read_text()) if (AN / "summary_main.json").exists() else {}
    for m, M in MODEL.items():
        r = summ.get(m)
        add(f"N{M}", r["n"] if r else "??")
        for s, S in STRAT.items():
            v = r["strategies"][s] if r else None
            add(f"Acc{S}{M}", pct(v and v["accuracy"]))
            add(f"Tok{S}{M}", f"{v['tokens_per_q']:,.0f}" if v else "??")
        for a, b in [("multi3", "indep3"), ("critique3", "indep3"), ("indep3", "direct")]:
            c = r["contrasts"][f"{a}-{b}"] if r else None
            k = f"{STRAT[a]}Minus{STRAT[b]}{M}"
            add(f"D{k}", pp(c and c["delta"]))
            add(f"D{k}Lo", pp(c and c["ci95"][0]))
            add(f"D{k}Hi", pp(c and c["ci95"][1]))
            add(f"P{k}", "??" if not c else ("<0.001" if c["p_exact"] < 0.001 else f"{c['p_exact']:.2g}"))
        d = r["disagreement"] if r else None
        add(f"DisFrac{M}", pct(d and d["frac"], 0))
        for s, S in STRAT.items():
            add(f"DisAcc{S}{M}", pct(d and d[s]["rate"], 0))
        t = r["transitions"] if r else None
        for s, S in [("critique3", "Critique"), ("multi3", "Debate")]:
            add(f"Rescue{S}{M}", pct(t and t[f"{s}_vs_indep3"]["rescue"]["rate"], 0))
            add(f"Corrupt{S}{M}", pct(t and t[f"{s}_vs_indep3"]["corruption"]["rate"], 0))
        for cat, C in [("SeqQA", "SeqQA"), ("ProtocolQA", "Protocol"), ("SeqQA2", "SeqQAII")]:
            bc = r["by_category"].get(cat) if r else None
            add(f"CritMinusVote{C}{M}", pp(bc and bc["critique3"] - bc["indep3"], 0))
    # sensitivity: GPT-OSS without the Groq-served questions; pooled contrasts over the three main models
    import numpy as np
    import analyze as AN_
    oss = [r for r in AN_.per_question("gpt-oss-120b", "main") if r.get("provider") == "primary"]
    if oss:
        so = AN_.analyze(oss)["contrasts"]["multi3-indep3"]
        add("NOSSNoGroq", len(oss))
        add("DDebateMinusVoteOSSNoGroq", pp(so["delta"]))
    pooled = [r for m in MODEL for r in AN_.per_question(m, "main")]
    by = {}
    for m in MODEL:
        by[m] = AN_.per_question(m, "main")
    rng = np.random.default_rng(AN_.BOOT_SEED)
    for a, b, K in [("critique3", "indep3", "CritiqueMinusVote"), ("multi3", "indep3", "DebateMinusVote"),
                    ("indep3", "direct", "VoteMinusDirect")]:
        diffs = {m: np.array([r[f"{a}_correct"] - r[f"{b}_correct"] for r in rr], float) for m, rr in by.items() if rr}
        allv = np.concatenate(list(diffs.values()))
        bs = [np.concatenate([v[rng.integers(0, len(v), len(v))] for v in diffs.values()]).mean() for _ in range(10000)]
        add(f"DPooled{K}", pp(allv.mean()))
        add(f"DPooled{K}Lo", pp(np.percentile(bs, 2.5)))
        add(f"DPooled{K}Hi", pp(np.percentile(bs, 97.5)))
    add("NPooled", len(pooled))
    # think vs talk (first 30)
    tvt = json.loads((AN / "think_vs_talk.json").read_text()) if (AN / "think_vs_talk.json").exists() else {}
    for fam, F in FAM.items():
        for arm, v in tvt.get(fam, {}).items():
            if "@" in arm and "-" not in arm:
                s, eff = arm.split("@")
                add(f"T{STRAT[s]}{eff.capitalize()}{F}", pct(v["acc"], 0))
                add(f"TTok{STRAT[s]}{eff.capitalize()}{F}", f"{v['gen_tokens']:,.0f}")
    for fam, F in FAM.items():
        a = tvt.get(fam, {})
        if "direct@low" in a and "direct@high" in a:
            add(f"TokRatio{F}", f"{a['direct@high']['gen_tokens'] / max(a['direct@low']['gen_tokens'], 1):.0f}")
    # ceiling
    ce = json.loads((AN / "ceiling.json").read_text()) if (AN / "ceiling.json").exists() else {}
    for key, K in [("first30_all_arms", "Thirty"), ("main_models", "Main")]:
        v = ce.get(key)
        add(f"ItemShare{K}", pct(v and v["item_share"], 0))
        add(f"ArmShare{K}", pct(v and v["arm_share"], 1))
        add(f"ItemShare{K}Lo", pct(v and v["item_ci95"][0], 0))
        add(f"ItemShare{K}Hi", pct(v and v["item_ci95"][1], 0))
        add(f"ArmShare{K}Lo", pct(v and v["arm_ci95"][0], 1))
        add(f"ArmShare{K}Hi", pct(v and v["arm_ci95"][1], 1))
        add(f"NArms{K}", v["n_arms"] if v else "??")
        add(f"NItems{K}", v["n_items"] if v else "??")
    mm = ce.get("main_models", {})
    u = mm.get("unsolved_by_category", {})
    add("NUnsolved", mm.get("n_unsolved", "??"))
    add("NAllSolved", mm.get("n_all_solved", "??"))
    add("NUnsolvedRecall", u.get("LitQA2", 0) + u.get("DbQA", 0) if u else "??")
    add("NUnsolvedSeqQAII", u.get("SeqQA2", 0) if u else "??")
    (PAPER / "numbers.tex").write_text("\n".join(L) + "\n")

    # prompt appendix, generated from the actual code
    task = {"question": "{QUESTION}", "answer_instruction": "{ANSWER INSTRUCTION}"}
    blocks = [
        ("Direct / Independent$\\times$3 / Critique call 1 (solve)", ST.solve_prompt(task)),
        ("Critique call 2 (critique)", ST.critique_prompt(task, "{CALL 1 OUTPUT}")),
        ("Critique call 3 (revise)", ST.revise_prompt(task, "{CALL 1 OUTPUT}", "{CALL 2 OUTPUT}")),
        ("Debate call 1 (researcher)", ST.solve_prompt(task, "researcher")),
        ("Debate call 2 (skeptic)", ST.solve_prompt(task, "skeptic")),
        ("Debate call 3 (adjudicator)", ST.adjudicate_prompt(task, "{CALL 1 OUTPUT}", "{CALL 2 OUTPUT}")),
    ]
    A = []
    for title, text in blocks:
        A.append(f"\\paragraph{{{title}}}\n\\begin{{footnotesize}}\\begin{{verbatim}}\n{wrap(text)}\n\\end{{verbatim}}\\end{{footnotesize}}")
    (PAPER / "prompts_appendix.tex").write_text("\n\n".join(A) + "\n")
    print(f"wrote {len(L) - 1} macros and {len(blocks)} prompt blocks")


def wrap(text: str, width: int = 110) -> str:
    out = []
    for line in text.split("\n"):
        while len(line) > width:
            cut = line.rfind(" ", 0, width)
            cut = cut if cut > 0 else width
            out.append(line[:cut])
            line = line[cut:].lstrip()
        out.append(line)
    return "\n".join(out)


if __name__ == "__main__":
    main()
